name: generate gh contributions svg snake animation

on:
  schedule:
    - cron: '0 */12 * * *'  # Ejecuta cada 12 horas
  workflow_dispatch: # Permite ejecutar manualmente la acci√≥n
  push:
    branches:
      - master  # Ejecuta cuando hay un push en la rama master

jobs:
  generate-svgs:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: push github-contribution-grid-snake.svg to the output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output  # Sube los archivos a la rama output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}